apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-scanning-filters-2
  namespace: {{ template "datree.namespace" . }}
data:
  datreeSkipList: |-
  {{- range  .Values.datree.customSkipList }}
- {{ . }}
  {{- end }}
