apiVersion: batch/v1
kind: Job
metadata:
  name: datree-cleanup-namespaces-hook-pre-delete
  labels: {{include "datree.labels" . | nindent 4}}
  namespace: {{template "datree.namespace" .}}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
    "helm.sh/hook": pre-delete, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
    {{- with .Values.customAnnotations }}
    {{ toYaml . }}
    {{- end}}
spec:
  ttlSecondsAfterFinished: {{.Values.hooks.ttlSecondsAfterFinished | default "1" }}
  template:
    metadata:
      labels: {{include "datree.labels" . | nindent 8}}
      {{- with .Values.customAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: OnFailure
      serviceAccount: datree-cleanup-namespaces-hook-pre-delete
      nodeSelector:
        kubernetes.io/os: linux
      {{- if .Values.imageCredentials.enabled }}
      imagePullSecrets:
        - name: datree-repo-credentials
      {{- end }}
      containers:
        - name: kubectl-label
          image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          imagePullPolicy: {{.Values.hooks.image.pullPolicy}}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - sh
            - "-c"
            - >-
              kubectl get ns;
