name: Helm Docs Validation
on:
  pull_request:
    branches:
      - main

jobs:
  helm_docs_validation:
    runs-on: ubuntu-latest
    container:
      image: jnorwood/helm-docs:v1.11.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Helm Docs
        uses: docker://jnorwood/helm-docs:latest
#        run: ls -la
#        run: sh ci/helm-docs.sh

      - name: Check for file changes
        run: |
          if [ -n "$(git diff)" ]; then
            echo "::error::helm-docs-validation failed, did you forget to run 'make generate-helm-docs'?"
            exit 1
          fi
