name: Release Tag
on:
  workflow_dispatch:
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: define_version
        name: Define release version
        run: |-
          OUTPUT_VERSION=$(bash scripts/define_release_version.sh)
          echo "detected version = $OUTPUT_VERSION"
          echo ::set-output name=version::$(echo $OUTPUT_VERSION)
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.define_version.outputs.version }}
          message: "Latest release"
