name: Release to Prod
on:
  workflow_dispatch:
jobs:
  release-docker:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: datree
      IMAGE_NAME: admission-webhook
    name: Release container image to public registries
    steps:
      - uses: actions/checkout@v3
      - name: Define release version
        id: define_version
        run: |-
          OUTPUT_VERSION=$(bash scripts/define_release_version.sh)
          echo "detected version = $OUTPUT_VERSION"
          echo ::set-output name=version::$(echo $OUTPUT_VERSION)
      - uses: actions/checkout@v3
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update version
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(with(select(.spec.template.spec.containers[0].image);.spec.template.spec.containers[0].image = "${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$OUTPUT_VERSION"))' 'deployment/admission-webhook-datree.yaml'
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build: Automated Change - Bump webhook-image version to ${{ steps.define_version.outputs.version }}'

